#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2023
# 
# 
# 
#

name: EmuELEC-CI

on:
  push:
    branches: 
      - dev
  # schedule:
  #   - cron: 0 20 * * *
  release:
    types: [published]

jobs:

  build_emuelec:

    name: Build EmuELEC firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update
          sudo -E apt -y install gcc make git unzip wget xz-utils libsdl2-dev libsdl2-mixer-dev libfreeimage-dev libfreetype6-dev libcurl4-openssl-dev rapidjson-dev libasound2-dev libgl1-mesa-dev build-essential libboost-all-dev cmake fonts-droid-fallback libvlc-dev libvlccore-dev vlc-bin texinfo premake4 golang libssl-dev curl patchelf xmlstarlet default-jre xsltproc
          sudo -E apt -y install tzdata xfonts-utils lzop
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h

      - name: Compile EmuELEC
        run: |
          PROJECT=Amlogic-ce DEVICE=Amlogic-ng ARCH=aarch64 DISTRO=EmuELEC make -j$(nproc) image || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1


      - name: Deliver EmuELEC
        uses: actions/upload-artifact@v2
        with:
          name: EmuELEC_firmware
          path: ./target
